name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python version
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Create virtual environment
      run: |
        python -m venv antenv

    - name: Install dependencies
      run: |
        antenv/bin/pip install --upgrade pip
        antenv/bin/pip install -r requirements.txt
        antenv/bin/pip install .

    - name: Zip the application files
      run: |
        zip -r app.zip . -x '*.git*' -x '__pycache__/*'
        

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'brevityprogram'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: app.zip
        custom_build_command: 'oryx build --platform python --platform-version 3.9 -i /github/workspace -o /github/workspace -p virtualenv_name=antenv'

